---
name: CI
on: [push, pull_request, workflow_dispatch]
jobs:
  build:
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v7
        with:
          token: ${{ secrets.OAPICF_GITHUB_TOKEN }}
      - uses: actions/setup-node@v7
        with:
          node-version: '22'
      - uses: cliffano/command-docker-action@v2.0.0
        with:
          command: 'make ci'
          image: cliffano/studio
          shell: bash
      - run: npm install -g gh-pages
      - run: CACHE_DIR=/tmp gh-pages --dist doc/ --user "pakkunbot <pakkunbot@users.noreply.github.com>" --repo "https://cliffano:${{ secrets.OAPICF_GITHUB_TOKEN }}@github.com/oapicf/minecraft-versions.git"
