name: Publish Python
'on':
  push:
    tags:
      - '*'
jobs:
  build:
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v7
        with:
          ref: main
      - uses: ./.github/actions/publish-python-action
        env:
          PYPI_TOKEN: ${{ secrets.OAPICF_PYPI_TOKEN }}
